### ISSUE TITLE
ERROR BootStrap  - Startup failed :(

### ISSUE THREAD

**Issue by owenmorgan** [Teevity/ice#268]
Hi all, im getting this error when attempting to start ICE, ive checked the s3 buckets and keys are fine.. at a loss now. Anyone able to help?

Thanks, 

```
2017-09-11 20:23:49,124 [main] INFO  http11.Http11NioProtocol  - Initializing ProtocolHandler ["http-nio-8080"]
2017-09-11 20:23:49,172 [main] INFO  net.NioSelectorPool  - Using a shared selector for servlet write/read
2017-09-11 20:23:49,209 [main] INFO  core.StandardService  - Starting service Tomcat
2017-09-11 20:23:49,210 [main] INFO  core.StandardEngine  - Starting Servlet Engine: Apache Tomcat/8.0.20
2017-09-11 20:23:49,406 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStatic] to [false] as the property does not exist.
2017-09-11 20:23:49,420 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopThreads] to [false] as the property does not exist.
2017-09-11 20:23:49,421 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesStopTimerThreads] to [false] as the property does not exist.
2017-09-11 20:23:49,422 [localhost-startStop-1] INFO  core.StandardContext  - Unable to set the web application class loader property [clearReferencesHttpClientKeepAliveThread] to [true] as the property does not exist.
2017-09-11 20:23:49,440 [localhost-startStop-1] INFO  startup.ContextConfig  - No global web.xml found
2017-09-11 20:23:49,594 [localhost-startStop-1] INFO  [localhost].[/ice]  - No Spring WebApplicationInitializer types detected on classpath
2017-09-11 20:23:49,633 [localhost-startStop-1] INFO  [localhost].[/ice]  - Initializing Spring root WebApplicationContext
2017-09-11 20:23:55,469 [localhost-startStop-1] INFO  context.GrailsConfigUtils  - [GrailsContextLoader] Grails application loaded.
2017-09-11 20:23:55,523 [localhost-startStop-1] INFO  BootStrap  - Starting ice...
| Error java.lang.NullPointerException
| Error         at java.util.Hashtable.put(Hashtable.java:459)
| Error         at java.util.Properties.setProperty(Properties.java:166)
| Error         at java_util_Properties$setProperty$2.call(Unknown Source)
| Error         at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
| Error         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
| Error         at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
| Error         at BootStrap$_closure1.doCall(BootStrap.groovy:148)
| Error         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
| Error         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
| Error         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
| Error         at java.lang.reflect.Method.invoke(Method.java:498)
| Error         at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
| Error         at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1207)
| Error         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1081)
| Error         at groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110)
| Error         at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1016)
| Error         at groovy.lang.Closure.call(Closure.java:423)
| Error         at groovy.lang.Closure.call(Closure.java:417)
| Error         at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
| Error         at grails.util.Environment.executeForEnvironment(Environment.java:320)
| Error         at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
| Error         at org.codehaus.groovy.grails.commons.DefaultGrailsBootstrapClass.callInit(DefaultGrailsBootstrapClass.java:60)
| Error         at org.codehaus.groovy.grails.web.context.GrailsConfigUtils.executeGrailsBootstraps(GrailsConfigUtils.java:78)
| Error         at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:110)
| Error         at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
| Error         at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
| Error         at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5162)
| Error         at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
| Error         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
| Error         at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
| Error         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
| Error         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
| Error         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
| Error         at java.lang.Thread.run(Thread.java:748)
| Error 2017-09-11 20:23:55,712 [localhost-startStop-1] ERROR BootStrap  - Startup failed
Message: null
    Line | Method
->>  459 | put                              in java.util.Hashtable
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
|    166 | setProperty                      in java.util.Properties
|    148 | doCall . . . . . . . . . . . . . in BootStrap$_closure1
|    327 | evaluateEnvironmentSpecificBlock in grails.util.Environment
|    320 | executeForEnvironment . . . . .  in     ''
|    296 | executeForCurrentEnvironment     in     ''
|    266 | run . . . . . . . . . . . . . .  in java.util.concurrent.FutureTask
|   1142 | runWorker                        in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . . . . . . . . . . . .  in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run                              in java.lang.Thread
```

**Comment by CpuID** [comment]
Getting the same thing here...

**Comment by CpuID** [comment]
I think I've fixed my issue, missing the [billing S3 bucket region config option](https://github.com/Teevity/ice/commit/03073a3e82d0a5b8689676376c73b6b0c5398f75), added approx 2 yrs ago.

@owenmorgan I was led by google to https://groups.google.com/forum/#!topic/iceusers/amt6c1TwqKw - which told me the issue is at a specific line# of [BootStrap.groovy](https://github.com/Teevity/ice/blob/master/grails-app/conf/BootStrap.groovy#L148) - in your case the same line as mine.

A search of this repo led me to the [named option in ice.properties](https://github.com/Teevity/ice/blob/eb33426da1c5671f756c835a239ada8c8743a366/src/java/com/netflix/ice/common/IceOptions.java#L57) that I need to set.

**Comment by owenmorgan** [comment]
yep! I found the same thread not long after. thanks for sharing
